[package]
name = "balance-book"
version = "1.0.0"
description = "Keep track of personal income expenses"
authors = ["Zane Kissel"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "updater", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
diesel = { version = "2.1.6", default-features = false, features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1.0"
homedir = "0.2.1"
argon2 = "0.5.3"
uuid = "1.8.0"
plaid = "8.0.0"
dotenv = "0.15.0"
#dotenvy = "0.15.7"
open = "5.1.2"
tauri-plugin-oauth = "0.0.0-alpha.0"
chrono = "0.4.37"
##replace-for-windows-build##rusqlite = { version = "0.30.0", features = ["bundled"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
